window.TRACKSECURE_TRAILS = [
  {
    "id": "mount-kinabalu",
    "name": "Mount Kinabalu",
    "location": "Kundasang, Sabah",
    "district": "Kundasang",
    "difficulty": "hard",
    "difficultyLabel": "Hard",
    "distance": "8.7 km",
    "duration": "2 Days",
    "elevation": "4,095 m",
    "type": "Out and Back",
    "latitude": 6.0753,
    "longitude": 116.5588,
    "description": "Sabah’s highest mountain and most iconic guided summit climb.",
    "image": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "bukit-sosodikon",
    "name": "Bukit Sosodikon",
    "location": "Kundasang, Sabah",
    "district": "Kundasang",
    "difficulty": "easy",
    "difficultyLabel": "Easy",
    "distance": "1.5 km",
    "duration": "1 Hour",
    "elevation": "1,465 m",
    "type": "Loop Trail",
    "latitude": 5.9919,
    "longitude": 116.5762,
    "description": "A short beginner-friendly hill with panoramic Kundasang views.",
    "image": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "mount-silam",
    "name": "Mount Silam",
    "location": "Lahad Datu, Sabah",
    "district": "Lahad Datu",
    "difficulty": "medium",
    "difficultyLabel": "Medium",
    "distance": "4.8 km",
    "duration": "3 Hours",
    "elevation": "884 m",
    "type": "Forest Trail",
    "latitude": 4.9518,
    "longitude": 118.1826,
    "description": "A tropical rainforest trail known for biodiversity and observation areas.",
    "image": "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "bukit-kokol",
    "name": "Bukit Kokol",
    "location": "Kota Kinabalu, Sabah",
    "district": "Kota Kinabalu",
    "difficulty": "medium",
    "difficultyLabel": "Medium",
    "distance": "5 km",
    "duration": "3 Hours",
    "elevation": "800 m",
    "type": "Hill Trail",
    "latitude": 6.0174,
    "longitude": 116.2071,
    "description": "A highland route overlooking Kota Kinabalu and the coast.",
    "image": "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "bukit-bongol",
    "name": "Bukit Bongol",
    "location": "Kudat, Sabah",
    "district": "Kudat",
    "difficulty": "medium",
    "difficultyLabel": "Medium",
    "distance": "3.5 km",
    "duration": "2 Hours",
    "elevation": "420 m",
    "type": "Out and Back",
    "latitude": 6.6948,
    "longitude": 116.7835,
    "description": "A scenic northern Sabah hill route with open ridge views.",
    "image": "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "bukit-gemok",
    "name": "Bukit Gemok",
    "location": "Tawau, Sabah",
    "district": "Tawau",
    "difficulty": "easy",
    "difficultyLabel": "Easy",
    "distance": "1 km to canopy walkway",
    "duration": "~1 Hour",
    "elevation": "428 m",
    "type": "Loop Trail",
    "latitude": 4.3376,
    "longitude": 117.8908,
    "description": "Forest trekking route in Bukit Gemok Forest Reserve, known for the Titian Selara canopy walkway and views over Tawau.",
    "image": "https://sabahnites.com/wp-content/uploads/2022/08/145714720_177562024164280_8840149135487162573_n.jpg",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ],
    "imageCredit": "Photo: Sabahnites",
    "routeStatus": "Published trail information available; verify current access before hiking."
  },
  {
    "id": "mount-trusmadi",
    "name": "Mount Trusmadi",
    "location": "Tambunan, Sabah",
    "district": "Tambunan",
    "difficulty": "extreme",
    "difficultyLabel": "Extreme",
    "distance": "Varies",
    "duration": "2–4 Days",
    "elevation": "2,642 m",
    "type": "Expedition",
    "latitude": 5.553,
    "longitude": 116.514,
    "description": "A demanding mossy-forest expedition on Malaysia’s second-highest mountain.",
    "image": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "mount-tambuyukon",
    "name": "Mount Tambuyukon",
    "location": "Ranau, Sabah",
    "district": "Ranau",
    "difficulty": "extreme",
    "difficultyLabel": "Extreme",
    "distance": "Multi-day",
    "duration": "4–6 Days",
    "elevation": "2,579 m",
    "type": "Expedition",
    "latitude": 6.206,
    "longitude": 116.658,
    "description": "A remote and challenging expedition within the Kinabalu Park landscape.",
    "image": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "kinabalu-nature-trails",
    "name": "Kinabalu Park Nature Trails",
    "location": "Ranau, Sabah",
    "district": "Ranau",
    "difficulty": "easy",
    "difficultyLabel": "Easy",
    "distance": "Varies",
    "duration": "30 min–3 Hours",
    "elevation": "1,500 m",
    "type": "Nature Trail",
    "latitude": 6.0001,
    "longitude": 116.5409,
    "description": "A network of cool montane forest trails near park headquarters.",
    "image": "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "silau-silau",
    "name": "Silau-Silau Trail",
    "location": "Ranau, Sabah",
    "district": "Ranau",
    "difficulty": "easy",
    "difficultyLabel": "Easy",
    "distance": "Short",
    "duration": "1–2 Hours",
    "elevation": "Montane forest",
    "type": "Loop",
    "latitude": 6.001,
    "longitude": 116.541,
    "description": "A shaded forest trail with streams and mossy vegetation.",
    "image": "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "liwagu-river",
    "name": "Liwagu River Trail",
    "location": "Ranau, Sabah",
    "district": "Ranau",
    "difficulty": "medium",
    "difficultyLabel": "Medium",
    "distance": "Varies",
    "duration": "2–3 Hours",
    "elevation": "Montane forest",
    "type": "Point to Point",
    "latitude": 5.996,
    "longitude": 116.548,
    "description": "A forest route following sections of the Liwagu River.",
    "image": "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "kipungit-waterfall",
    "name": "Kipungit Waterfall Trail",
    "location": "Ranau, Sabah",
    "district": "Ranau",
    "difficulty": "easy",
    "difficultyLabel": "Easy",
    "distance": "Short",
    "duration": "30–60 min",
    "elevation": "Lowland forest",
    "type": "Out and Back",
    "latitude": 6.048,
    "longitude": 116.704,
    "description": "A short rainforest walk from Poring to Kipungit Waterfall.",
    "image": "https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "langanang-waterfall",
    "name": "Langanan Waterfall Trail",
    "location": "Ranau, Sabah",
    "district": "Ranau",
    "difficulty": "hard",
    "difficultyLabel": "Hard",
    "distance": "8 km return",
    "duration": "4–6 Hours",
    "elevation": "Rainforest",
    "type": "Out and Back",
    "latitude": 6.052,
    "longitude": 116.706,
    "description": "A longer rainforest route towards a scenic waterfall.",
    "image": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "salt-trail",
    "name": "Crocker Range Salt Trail",
    "location": "Penampang–Tambunan, Sabah",
    "district": "Penampang–Tambunan",
    "difficulty": "extreme",
    "difficultyLabel": "Extreme",
    "distance": "34 km",
    "duration": "3+ Days",
    "elevation": "Mountain forest",
    "type": "Point to Point",
    "latitude": 5.84,
    "longitude": 116.18,
    "description": "A historic long-distance village trail through Crocker Range.",
    "image": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "gunung-alab",
    "name": "Gunung Alab Trails",
    "location": "Tambunan, Sabah",
    "district": "Tambunan",
    "difficulty": "medium",
    "difficultyLabel": "Medium",
    "distance": "Varies",
    "duration": "1–4 Hours",
    "elevation": "1,900 m",
    "type": "Nature Trail",
    "latitude": 5.81,
    "longitude": 116.34,
    "description": "Cool highland forest trails with mist and mossy plants.",
    "image": "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "mahua-waterfall",
    "name": "Mahua Waterfall Trail",
    "location": "Tambunan, Sabah",
    "district": "Tambunan",
    "difficulty": "easy",
    "difficultyLabel": "Easy",
    "distance": "Short",
    "duration": "30–60 min",
    "elevation": "Highland forest",
    "type": "Out and Back",
    "latitude": 5.78,
    "longitude": 116.39,
    "description": "A convenient forest path to the scenic Mahua Waterfall.",
    "image": "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "bukit-perahu",
    "name": "Bukit Perahu",
    "location": "Tamparuli, Sabah",
    "district": "Tamparuli",
    "difficulty": "medium",
    "difficultyLabel": "Medium",
    "distance": "3–5 km",
    "duration": "1–3 Hours",
    "elevation": "Hill summit",
    "type": "Out and Back",
    "latitude": 6.132,
    "longitude": 116.275,
    "description": "A popular sunrise hill overlooking Tamparuli valleys.",
    "image": "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "gaya-island",
    "name": "Gaya Island Nature Trails",
    "location": "Kota Kinabalu, Sabah",
    "district": "Kota Kinabalu",
    "difficulty": "medium",
    "difficultyLabel": "Medium",
    "distance": "Varies",
    "duration": "1–5 Hours",
    "elevation": "Island forest",
    "type": "Point to Point",
    "latitude": 6.018,
    "longitude": 116.038,
    "description": "Island jungle trails connecting forests, beaches and coastal areas.",
    "image": "https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "piniapat-hill",
    "name": "Piniapat Hill",
    "location": "Pitas, Sabah",
    "district": "Pitas",
    "difficulty": "medium",
    "difficultyLabel": "Medium",
    "distance": "Short",
    "duration": "1–2 Hours",
    "elevation": "Coastal hill",
    "type": "Out and Back",
    "latitude": 6.72,
    "longitude": 117.02,
    "description": "A scenic coastal hill known for sunrise and sunset views.",
    "image": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "danum-valley",
    "name": "Danum Valley Jungle Trails",
    "location": "Lahad Datu, Sabah",
    "district": "Lahad Datu",
    "difficulty": "medium",
    "difficultyLabel": "Medium",
    "distance": "Varies",
    "duration": "1 Hour–Full Day",
    "elevation": "Lowland rainforest",
    "type": "Guided Trails",
    "latitude": 4.96,
    "longitude": 117.8,
    "description": "Guided rainforest trekking with wildlife, rivers and ancient forest.",
    "image": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "tabin-wildlife",
    "name": "Tabin Wildlife Reserve Trails",
    "location": "Lahad Datu, Sabah",
    "district": "Lahad Datu",
    "difficulty": "medium",
    "difficultyLabel": "Medium",
    "distance": "Varies",
    "duration": "Several Hours",
    "elevation": "Lowland rainforest",
    "type": "Guided Trails",
    "latitude": 5.22,
    "longitude": 118.68,
    "description": "Guided forest routes to wildlife areas and mud volcanoes.",
    "image": "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "table-waterfall",
    "name": "Table Waterfall Trail",
    "location": "Tawau Hills Park, Tawau, Sabah",
    "district": "Tawau",
    "difficulty": "easy",
    "difficultyLabel": "Easy",
    "distance": "~2.5 km",
    "duration": "~1.5–2 Hours",
    "elevation": "Lowland rainforest",
    "type": "Nature / Waterfall Trail",
    "latitude": 4.441917,
    "longitude": 118.022175,
    "description": "Rainforest trail to Table Waterfall (Bukit Gelas Waterfall area), a natural swimming pool and waterfall attraction in Tawau Hills Park.",
    "image": "https://sabahtravel-assets.s3.amazonaws.com/images/20240126-lmy8f-lk-05693-jpg",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ],
    "imageCredit": "Photo: SabahTravel",
    "routeStatus": "Published route information available; exact GPS line is not embedded in this app.",
    "routeSource": "https://sabahparks.org.my/tawau-hills-park/activities-facilities"
  },
  {
    "id": "bombalai-hill",
    "name": "Bombalai Hill Trail",
    "location": "Tawau Hills Park, Tawau, Sabah",
    "district": "Tawau",
    "difficulty": "hard",
    "difficultyLabel": "Hard",
    "distance": "~1.9 km one-way",
    "duration": "~1 Hour one-way",
    "elevation": "530 m",
    "type": "Jungle Trail / Volcanic Hill",
    "latitude": 4.3851,
    "longitude": 117.8806,
    "description": "Short jungle trail to the summit of Bombalai Hill, an extinct volcanic cone in Tawau Hills Park.",
    "image": "https://www.gunungbagging.com/wp-content/NEXTGEN/bombalai-hill/IMG_20230707_090142.jpg",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ],
    "imageCredit": "Photo: Gunung Bagging",
    "routeStatus": "Published trail map and waypoint route available.",
    "routeSource": "https://www.gunungbagging.com/wp-content/maps/peta-jalur-pendakian-bombalai-hill.pdf"
  },
  {
    "id": "maliau-basin",
    "name": "Maliau Basin Trek",
    "location": "Tongod, Sabah",
    "district": "Tongod",
    "difficulty": "extreme",
    "difficultyLabel": "Extreme",
    "distance": "Multi-day",
    "duration": "4–7 Days",
    "elevation": "Remote rainforest",
    "type": "Expedition",
    "latitude": 4.82,
    "longitude": 116.98,
    "description": "A demanding wilderness expedition through remote rainforest and waterfalls.",
    "image": "https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "imbak-canyon",
    "name": "Imbak Canyon Jungle Trek",
    "location": "Tongod, Sabah",
    "district": "Tongod",
    "difficulty": "hard",
    "difficultyLabel": "Hard",
    "distance": "Varies",
    "duration": "Multi-day",
    "elevation": "Remote rainforest",
    "type": "Guided Expedition",
    "latitude": 5.02,
    "longitude": 117.05,
    "description": "Remote jungle trekking within an important conservation landscape.",
    "image": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "batu-punggul",
    "name": "Batu Punggul Trek",
    "location": "Nabawan, Sabah",
    "district": "Nabawan",
    "difficulty": "hard",
    "difficultyLabel": "Hard",
    "distance": "Varies",
    "duration": "Several Hours",
    "elevation": "Limestone pinnacle",
    "type": "Guided Climb",
    "latitude": 4.73,
    "longitude": 116.48,
    "description": "A jungle approach followed by a steep limestone adventure.",
    "image": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    "parking": "Check with the trail operator or park office.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities vary by location.",
    "permit": "Check current permit and guide requirements.",
    "fee": "Fees may apply.",
    "signal": "May be limited in forest or mountain areas.",
    "recommended": "Choose according to fitness and hiking experience.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Headlamp",
      "Mobile phone"
    ],
    "tips": [
      "Check weather before departure.",
      "Inform someone about your route.",
      "Stay on marked trails.",
      "Do not hike alone in remote areas.",
      "Carry out all rubbish."
    ]
  },
  {
    "id": "bukit-panchang",
    "name": "Bukit Panchang",
    "location": "Tawau, Sabah",
    "district": "Tawau",
    "difficulty": "medium",
    "difficultyLabel": "Medium",
    "distance": "1.08 km",
    "duration": "1–2 Hours",
    "elevation": "398 m",
    "type": "Out and Back",
    "latitude": 4.25434,
    "longitude": 117.97473,
    "description": "A short but steep hill trail in Tawau with rewarding views from the summit. The published trail information identifies the trailhead near Tinagat and provides a dedicated hiking route.",
    "image": "https://www.mysabah.com/wordpress/wp-content/uploads/2023/12/20231222_27.jpg",
    "parking": "Roadside parking near the trailhead; follow local signs and access guidance.",
    "water": "Bring sufficient drinking water; no dependable water source should be assumed on the trail.",
    "toilet": "Toilets are reported at the trailhead.",
    "permit": "Permit required; check current requirements with Jabatan Perhutanan Sabah, Tawau.",
    "fee": "Published hiking information reports RM5 for Malaysians and RM15 for non-Malaysians; verify current fees before hiking.",
    "signal": "Mobile signal may vary along the route.",
    "recommended": "Suitable for hikers with basic to moderate fitness; the climb is short but steep.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Mobile phone",
      "Sun protection"
    ],
    "tips": [
      "Start early because Tawau can be hot and humid.",
      "Check weather before departure.",
      "Confirm permit and guide requirements before hiking.",
      "Stay on the established trail.",
      "Carry out all rubbish."
    ],
    "imageCredit": "Photo: MySabah.com",
    "routeStatus": "Published route description available; ranger guidance is required according to the source.",
    "routeSource": "https://www.mysabah.com/wordpress/bukit-panchang-tinagat/"
  },
  {
    "id": "bukit-membalua",
    "name": "Membalua Jungle Trek",
    "location": "Tawau, Sabah",
    "district": "Tawau",
    "difficulty": "medium",
    "difficultyLabel": "Medium",
    "distance": "Varies",
    "duration": "Varies",
    "video": "videos/bukit-membalua.mp4",
    "elevation": "166 m (forest reserve reference)",
    "type": "Forest / Local Trail",
    "latitude": 4.2724,
    "longitude": 118.0043,
    "description": "A recreation and forest area in the Membalua Forest Reserve where walking, jogging, hiking and camping activities are reported. The exact hiking loop is not published in the source, so the app does not invent a GPS track.",
    "image": "https://www.etawau.com/NaturalResources/Forest/MembaluaReserve/MembaluaReserve/Membalua_2014_08P2000.jpg",
    "parking": "Access and parking depend on the selected local entry point.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities are not confirmed at the forest reserve reference point.",
    "permit": "Check with the relevant Sabah forestry authority or land manager before entering.",
    "fee": "Not confirmed; verify before visiting.",
    "signal": "Signal may be limited in forested areas.",
    "recommended": "Use a local guide or verified route information and avoid entering restricted forest areas without permission.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Mobile phone",
      "Offline map"
    ],
    "tips": [
      "Verify the legal access point before hiking.",
      "Do not enter restricted forest areas.",
      "Check weather and trail conditions.",
      "Inform someone of your route.",
      "Carry out all rubbish."
    ],
    "imageCredit": "Photo: eTawau",
    "routeStatus": "Local trail area; exact GPS trek not verified in available source. Verify route and access locally.",
    "routeSource": "https://www.etawau.com/NaturalResources/Forest/MembaluaReserve/Membalua.htm"
  },
  {
    "id": "bukit-sin-onn",
    "name": "Sin Onn Hill",
    "location": "Tawau, Sabah",
    "district": "Tawau",
    "difficulty": "medium",
    "difficultyLabel": "Medium",
    "distance": "Varies",
    "duration": "Varies",
    "elevation": "Not confirmed",
    "type": "Local Hill / Jogging Trail",
    "latitude": 4.27743,
    "longitude": 117.91,
    "description": "A historic local hill and jogging destination around Sin On Road. Current access should be verified because the area has had private-land and quarry activity concerns.",
    "image": "https://www.etawau.com/Recreation/CrossCountry/Hill_b.jpg",
    "parking": "Use only designated or permitted parking areas near the current trail access.",
    "water": "Bring sufficient drinking water.",
    "toilet": "Facilities depend on the local trail access point.",
    "permit": "Check local landowner or authority requirements before entering.",
    "fee": "Not confirmed; verify before visiting.",
    "signal": "Signal may vary depending on the route.",
    "recommended": "Suitable for hikers who confirm the current route and access conditions before hiking.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Mobile phone",
      "Offline map"
    ],
    "tips": [
      "Confirm the current trailhead before departure.",
      "Respect private land and local access rules.",
      "Check weather before hiking.",
      "Avoid hiking alone on unfamiliar routes.",
      "Carry out all rubbish."
    ],
    "imageCredit": "Photo: eTawau",
    "routeStatus": "Historical hiking/jogging trail documented; current access and exact GPS route require local verification.",
    "routeSource": "https://www.etawau.com/HTML/Recreation/CrossCountry_Jogging.htm"
  },
  {
    "id": "lim-man-kui",
    "name": "Lim Man Kui Quarry Hill",
    "location": "Tawau, Sabah",
    "district": "Tawau",
    "difficulty": "medium",
    "difficultyLabel": "Medium",
    "distance": "Varies",
    "duration": "~2 Hours",
    "elevation": "Varies",
    "type": "Hill / Quarry Trail",
    "latitude": 4.287,
    "longitude": 117.907,
    "description": "A local Tawau hill track described as a popular hiking and Hash running route with rocky ground and panoramic views. Current land access should be confirmed before visiting.",
    "image": "https://www.etawau.com/Recreation/CrossCountry/Hill_b.jpg",
    "imageCredit": "Photo: eTawau",
    "parking": "Verify current parking and land access locally.",
    "water": "Bring sufficient water.",
    "toilet": "Not confirmed.",
    "permit": "Check landowner/authority requirements.",
    "fee": "No admission fee reported in the source; verify current access.",
    "signal": "May vary.",
    "recommended": "Experienced hikers or local group; verify current access.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Mobile phone",
      "Offline map"
    ],
    "tips": [
      "Confirm current access before hiking.",
      "Avoid quarry work areas.",
      "Check weather.",
      "Do not hike alone on unfamiliar routes.",
      "Carry out all rubbish."
    ],
    "routeStatus": "Historical route description available; exact GPS track not verified.",
    "routeSource": "https://www.etawau.com/HTML/Recreation/CrossCountry_Jogging.htm"
  },
  {
    "id": "sulphur-spring",
    "name": "Sulphur Spring Trail",
    "location": "Tawau Hills Park, Tawau, Sabah",
    "district": "Tawau",
    "difficulty": "easy",
    "difficultyLabel": "Easy",
    "distance": "~3.2–3.4 km",
    "duration": "~1 Hour",
    "elevation": "Not specified",
    "type": "Nature / Jungle Trail",
    "latitude": 4.39801,
    "longitude": 117.88826,
    "description": "A rainforest nature trail leading to the sulphur springs in Tawau Hills Park.",
    "image": "https://tempatcuti.my/wp-content/uploads/2023/12/kolam-air-panas-bukit-tawau.jpg",
    "imageCredit": "Photo: TempatCuti.my",
    "parking": "Tawau Hills Park facilities.",
    "water": "Bring drinking water.",
    "toilet": "Facilities at park areas; confirm before departure.",
    "permit": "Normal park entry; mountain permits are separate.",
    "fee": "Tawau Hills Park conservation fee applies; verify current rates.",
    "signal": "May be limited.",
    "recommended": "General visitors with basic fitness.",
    "preparation": [
      "Hiking shoes",
      "Drinking water",
      "Raincoat",
      "First aid kit",
      "Mobile phone"
    ],
    "tips": [
      "Stay on marked trails.",
      "Watch for slippery surfaces.",
      "Check weather before departure.",
      "Respect park rules.",
      "Carry out all rubbish."
    ],
    "routeStatus": "Published trail distance available; exact GPS line not embedded because the source does not provide a downloadable track.",
    "routeSource": "https://sabahparks.org.my/tawau-hills-park/activities-facilities"
  },
  {
    "id": "mt-lucia-tawau",
    "name": "Mount Lucia",
    "location": "Tawau Hills Park, Tawau, Sabah",
    "district": "Tawau",
    "difficulty": "extreme",
    "difficultyLabel": "Extreme",
    "distance": "~12 km",
    "duration": "2 Days 1 Night",
    "elevation": "1,202 m",
    "type": "Mountain Expedition",
    "latitude": 4.433,
    "longitude": 117.917,
    "description": "One of the three main mountain peaks in Tawau Hills Park. The mountain trail is a demanding rainforest route and should be undertaken with required registration and guide arrangements.",
    "image": "https://assets.nst.com.my/images/articles/030724nstSabah01-2_1719967922.jpg",
    "imageCredit": "Photo: New Straits Times / Tawau Hills Park",
    "parking": "Tawau Hills Park HQ / designated access.",
    "water": "Carry sufficient water and follow guide advice.",
    "toilet": "Facilities limited along mountain route.",
    "permit": "Climbing permit required.",
    "fee": "Climbing permit and insurance fees apply; verify current Sabah Parks rates.",
    "signal": "May be limited.",
    "recommended": "Experienced hikers with guide.",
    "preparation": [
      "Hiking shoes",
      "Rain gear",
      "Headlamp",
      "Water",
      "First aid kit",
      "Offline map",
      "Emergency contact"
    ],
    "tips": [
      "Register before climbing.",
      "Guide is compulsory for mountain routes.",
      "Check weather.",
      "Follow ranger/guide instructions.",
      "Do not hike alone."
    ],
    "routeStatus": "Official mountain route information available; use a current Sabah Parks guide/route plan rather than an invented GPS line.",
    "routeSource": "https://www.sabahparks.org.my/tawau-hills-park"
  },
  {
    "id": "mt-magdalena-tawau",
    "name": "Mount Magdalena",
    "location": "Tawau Hills Park, Tawau, Sabah",
    "district": "Tawau",
    "difficulty": "extreme",
    "difficultyLabel": "Extreme",
    "distance": "14 km",
    "duration": "3 Days 2 Nights",
    "elevation": "1,312 m",
    "type": "Mountain Expedition",
    "latitude": 4.435,
    "longitude": 117.954,
    "description": "The highest peak in Tawau Hills Park. Sabah Parks describes a 14 km forest trail and recommends a multi-day climb.",
    "image": "https://assets.nst.com.my/images/articles/030724nstSabah01-2_1719967922.jpg",
    "imageCredit": "Photo: New Straits Times / Tawau Hills Park",
    "parking": "Tawau Hills Park designated access.",
    "water": "Carry sufficient water; follow guide advice.",
    "toilet": "Limited on trail.",
    "permit": "Climbing permit required.",
    "fee": "Climbing permit and insurance fees apply; verify current rates.",
    "signal": "May be limited.",
    "recommended": "Experienced hikers with guide and proper preparation.",
    "preparation": [
      "Hiking shoes",
      "Rain gear",
      "Headlamp",
      "Water",
      "First aid kit",
      "Offline map"
    ],
    "tips": [
      "Register and obtain permit.",
      "Guide is compulsory.",
      "Plan for wet and cold conditions.",
      "Inform emergency contact.",
      "Carry out all rubbish."
    ],
    "routeStatus": "Official route distance is published; use current Sabah Parks route guidance for the exact track.",
    "routeSource": "https://sabahparks.org.my/tawau-hills-park/activities-facilities"
  },
  {
    "id": "mt-maria-tawau",
    "name": "Mount Maria",
    "location": "Tawau Hills Park, Tawau, Sabah",
    "district": "Tawau",
    "difficulty": "hard",
    "difficultyLabel": "Hard",
    "distance": "Varies",
    "duration": "2+ Days",
    "elevation": "1,083 m",
    "type": "Mountain Expedition",
    "latitude": 4.443,
    "longitude": 117.922,
    "description": "One of the three main mountain peaks in Tawau Hills Park. Climbing requires registration, permit and guide arrangements.",
    "image": "https://assets.nst.com.my/images/articles/030724nstSabah01-2_1719967922.jpg",
    "imageCredit": "Photo: New Straits Times / Tawau Hills Park",
    "parking": "Tawau Hills Park designated access.",
    "water": "Carry sufficient water.",
    "toilet": "Limited on mountain route.",
    "permit": "Climbing permit required.",
    "fee": "Climbing permit and insurance fees apply; verify current rates.",
    "signal": "May be limited.",
    "recommended": "Fit hikers with guide.",
    "preparation": [
      "Hiking shoes",
      "Rain gear",
      "Headlamp",
      "Water",
      "First aid kit",
      "Offline map"
    ],
    "tips": [
      "Register before climbing.",
      "Use a mountain guide.",
      "Check weather.",
      "Do not hike alone.",
      "Follow park rules."
    ],
    "routeStatus": "Official peak and permit information available; exact GPS track should be obtained from the current guide/park authority.",
    "routeSource": "https://www.sabahparks.org.my/tawau-hills-park"
  },
  {
    "id": "tiger-hill-tawau",
    "name": "Tiger Hill Trail",
    "location": "Tawau, Sabah",
    "district": "Tawau",
    "difficulty": "hard",
    "difficultyLabel": "Hard",
    "distance": "Varies",
    "duration": "5+ Hours",
    "elevation": "~387 m",
    "type": "Hill / Forest Trail",
    "latitude": 4.4285,
    "longitude": 117.8309,
    "description": "Tiger Hill is a volcanic cone in the Tawau volcanic field. A hiking route is documented online, but access may involve plantation/private land, so permission and current trail status must be verified.",
    "image": "https://www.etawau.com/Recreation/CrossCountry/Hill_b.jpg",
    "imageCredit": "Photo: eTawau (Tawau hiking archive)",
    "parking": "Verify current legal access and parking.",
    "water": "Bring sufficient water.",
    "toilet": "Not confirmed.",
    "permit": "Confirm landowner/authority permission.",
    "fee": "Not confirmed.",
    "signal": "May vary.",
    "recommended": "Experienced hikers with local knowledge.",
    "preparation": [
      "Hiking shoes",
      "Water",
      "Raincoat",
      "First aid kit",
      "Offline map",
      "Mobile phone"
    ],
    "tips": [
      "Get permission before entering private/plantation land.",
      "Use a verified local route.",
      "Check weather.",
      "Do not hike alone.",
      "Carry out all rubbish."
    ],
    "routeStatus": "Community GPS trail exists online, but current access should be verified before use.",
    "routeSource": "https://www.wikiloc.com/hiking-trails/tiger-hill-97314190"
  }
];
